[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile.prod"

[deploy]
startCommand = "./entrypoint.sh"
healthcheckPath = "/api/v1/health/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
