# Generated by Django 5.2 on 2026-05-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
