# Generated by Django 5.2 on 2026-09-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_add_phone_to_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('team_invite', 'Convite para equipe'), ('join_request', 'Pedido de entrada'), ('invite_accepted', 'Convite aceito'), ('invite_declined', 'Convite recusado'), ('join_accepted', 'Pedido aceito'), ('join_declined', 'Pedido recusado'), ('team_submitted', 'Equipe submetida'), ('team_approved', 'Equipe aprovada'), ('team_rejected', 'Equipe recusada'), ('team_disbanded', 'Equipe descartada'), ('application_confirmed', 'Inscrição confirmada'), ('stage_advanced', 'Convocação para próxima etapa'), ('application_approved', 'Aprovado no processo seletivo'), ('application_rejected', 'Não aprovado no processo seletivo'), ('custom_communication', 'Comunicado do processo seletivo')], max_length=30),
        ),
    ]
