from django.urls import path

from .views import (
    AdminApplicationDetailView,
    AdminApplicationListView,
    AdminBulkActionView,
    AdminCommunicationDetailView,
    AdminCommunicationListCreateView,
    AdminEvaluationView,
    AdminProcessCloseView,
    AdminProcessDetailView,
    AdminProcessListCreateView,
    AdminProcessPublishView,
    AdminStageAssignmentView,
    AdminStageAutoDistributeView,
    AdminStageDetailView,
    AdminStageListCreateView,
    AdminStageReorderView,
    MyApplicationDetailView,
    MyApplicationListView,
    ProcessApplyView,
    ProcessDetailView,
    ProcessListView,
)

urlpatterns = [
    # ── Candidato ────────────────────────────────────────────────
    path('processes/', ProcessListView.as_view(), name='processes'),
    path('processes/<uuid:pk>/', ProcessDetailView.as_view(), name='process-detail'),
    path(
        'processes/<uuid:pk>/apply/',
        ProcessApplyView.as_view(),
        name='process-apply',
    ),
    path('me/applications/', MyApplicationListView.as_view(), name='my-applications'),
    path(
        'me/applications/<uuid:pk>/',
        MyApplicationDetailView.as_view(),
        name='my-application-detail',
    ),
    # ── Organizador ──────────────────────────────────────────────
    path(
        'admin/processes/',
        AdminProcessListCreateView.as_view(),
        name='admin-processes',
    ),
    path(
        'admin/processes/<uuid:pk>/',
        AdminProcessDetailView.as_view(),
        name='admin-process-detail',
    ),
    path(
        'admin/processes/<uuid:pk>/publish/',
        AdminProcessPublishView.as_view(),
        name='admin-process-publish',
    ),
    path(
        'admin/processes/<uuid:pk>/close/',
        AdminProcessCloseView.as_view(),
        name='admin-process-close',
    ),
    path(
        'admin/processes/<uuid:pk>/stages/',
        AdminStageListCreateView.as_view(),
        name='admin-stages',
    ),
    path(
        'admin/processes/<uuid:pk>/stages/reorder/',
        AdminStageReorderView.as_view(),
        name='admin-stages-reorder',
    ),
    path(
        'admin/stages/<uuid:pk>/',
        AdminStageDetailView.as_view(),
        name='admin-stage-detail',
    ),
    path(
        'admin/processes/<uuid:pk>/applications/',
        AdminApplicationListView.as_view(),
        name='admin-applications',
    ),
    path(
        'admin/applications/<uuid:pk>/',
        AdminApplicationDetailView.as_view(),
        name='admin-application-detail',
    ),
    path(
        'admin/applications/<uuid:pk>/evaluations/',
        AdminEvaluationView.as_view(),
        name='admin-application-evaluations',
    ),
    path(
        'admin/processes/<uuid:pk>/applications/bulk-action/',
        AdminBulkActionView.as_view(),
        name='admin-bulk-action',
    ),
    path(
        'admin/processes/<uuid:pk>/communications/',
        AdminCommunicationListCreateView.as_view(),
        name='admin-communications',
    ),
    path(
        'admin/communications/<uuid:pk>/',
        AdminCommunicationDetailView.as_view(),
        name='admin-communication-detail',
    ),
    path(
        'admin/stages/<uuid:pk>/assignments/',
        AdminStageAssignmentView.as_view(),
        name='admin-stage-assignments',
    ),
    path(
        'admin/stages/<uuid:pk>/assignments/auto/',
        AdminStageAutoDistributeView.as_view(),
        name='admin-stage-auto-distribute',
    ),
]
