# Generated by Django 5.2 on 2026-09-16 00:47

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='process_banners/')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('closed', 'Encerrado')], default='draft', max_length=20)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('highlight_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processo seletivo',
                'verbose_name_plural': 'Processos seletivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('discarded', 'Descartado')], default='in_progress', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='teams.participant')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.process')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ['participant__full_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role_title', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de organizador',
                'verbose_name_plural': 'Perfis de organizador',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('accepts_late_submission', models.BooleanField(default=False)),
                ('allows_file_upload', models.BooleanField(default=False)),
                ('max_files', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allowed_file_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='recruitment.process')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='recruitment.stage')),
            ],
            options={
                'verbose_name': 'Critério de avaliação',
                'verbose_name_plural': 'Critérios de avaliação',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='recruitment.application')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='recruitment.evaluationcriterion')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='recruitment.stage')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['stage__order', 'criterion__order'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='deliverables/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='recruitment.application')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='recruitment.stage')),
            ],
            options={
                'verbose_name': 'Entregável',
                'verbose_name_plural': 'Entregáveis',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('auto', 'Automática'), ('manual', 'Manual')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Todos os candidatos'), ('stage', 'Todos de uma etapa'), ('approved', 'Apenas aprovados'), ('rejected', 'Apenas reprovados'), ('specific', 'Candidatos específicos')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Enviada'), ('failed', 'Falhou')], default='sent', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(blank=True, related_name='communications', to='teams.participant')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='recruitment.process')),
                ('audience_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='recruitment.stage')),
            ],
            options={
                'verbose_name': 'Comunicação',
                'verbose_name_plural': 'Comunicações',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_applications', to='recruitment.stage'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('process', 'order'), name='unique_stage_order_per_process'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('application', 'criterion', 'evaluator'), name='unique_evaluation_per_criterion_and_evaluator'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('process', 'participant'), name='unique_application_per_process'),
        ),
    ]
