# Generated by Django 5.2 on 2026-09-16 17:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationcriterion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='is_coordinator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='anonymous_evaluation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='process',
            name='divergence_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4),
        ),
        migrations.AddField(
            model_name='process',
            name='score_max',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='process',
            name='score_min',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stage',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='StageAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='recruitment.application')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_assignments', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='recruitment.stage')),
            ],
            options={
                'verbose_name': 'Designação de avaliador',
                'verbose_name_plural': 'Designações de avaliador',
                'ordering': ['stage__order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('stage', 'application', 'evaluator'), name='unique_assignment_per_stage_application_evaluator')],
            },
        ),
    ]
