# Generated by Django 5.2 on 2026-09-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_application_code_evaluationcriterion_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
