# Generated by Django 5.2 on 2026-09-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_stage_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='instructions_file',
            field=models.FileField(blank=True, upload_to='enunciados/%Y/%m/'),
        ),
    ]
