# Generated by Django 5.2 on 2026-09-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_stage_instructions_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em andamento'), ('approved', 'Aprovado'), ('rejected', 'Reprovado'), ('discarded', 'Descartado'), ('withdrawn', 'Desistiu')], default='in_progress', max_length=20),
        ),
    ]
