# Generated by Django 5.2 on 2026-09-20 12:43
"""Liga a correção anônima do case nos processos que já existiam.

O blueprint passou a marcar a etapa do case como anônima, mas ele só vale para
processo novo: `ensure_selection_process` não altera processo existente, de
propósito, para não desfazer ajuste do organizador. Sem esta migração, o
processo que já está no ar continuaria com a caixa desmarcada e o anonimato
seria um recurso que ninguém sabe que precisa ligar.

Mexe só na etapa do case, e só onde nenhuma etapa do processo estava marcada:
se alguém já tinha escolhido, a escolha fica.
"""

from django.db import migrations

NOME_DO_CASE = 'Resolução do Case'


def ligar(apps, schema_editor):
    Process = apps.get_model('recruitment', 'Process')
    for process in Process.objects.all():
        if process.stages.filter(anonymous_evaluation=True).exists():
            continue
        process.stages.filter(name=NOME_DO_CASE).update(anonymous_evaluation=True)


def desligar(apps, schema_editor):
    """Volta atrás desmarcando o case, que é tudo o que esta migração marcou."""
    Stage = apps.get_model('recruitment', 'Stage')
    Stage.objects.filter(name=NOME_DO_CASE).update(anonymous_evaluation=False)


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_remove_process_anonymous_evaluation_and_more'),
    ]

    operations = [
        migrations.RunPython(ligar, desligar),
    ]
